[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Optimizer settings
optimizer = true
runs = 200

# Remappings for dependencies
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/",
    "@foundry-devops/=lib/foundry-devops/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
